config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  devise_scope :user do 
    get "users", to: "devise/sessions#new"
  end
  
  # Defines the root path route ("/")
  root "events#index"

  # Users
  resources :users, only: :show
  
  # Events
  resources :events do
    #Invites - Inviters
    resources :invites, only: :create do
      collection do
        get '', to: 'invites#manage' # GET events/:event_id/invites
        delete '', to: 'invites#revoke' # DELETE events/:event_id/invites
      end
    end

    # Attendances
    resources :attendances, only: :create do
      delete '', to: 'attendances#destroy', on: :collection # DELETE events/:event_id/attendances
    end
  end

  # Invites - Invitees
  resources :invites, only: :index do
    member do
      post 'accept' # POST invites/:id/accept
      post 'decline' # POST invites/:id/decline
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include Attendable

  validates :name, :datetime_of, :location, presence: true 
  validates :datetime_of, comparison: { greater_than: DateTime.current, message: "must be in the future!" }
  
  belongs_to :host, class_name: "User"
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances

  has_many :invites, dependent: :destroy
  has_many :invitees, through: :invites

  attr_accessor :current_user

  # Past/Future Events
  scope :past, -> { where("datetime_of < ?", DateTime.now) }
  scope :future, -> { where("datetime_of > ?", DateTime.now) }

  # Format Event Date/Time
  def date_of
    datetime_of.strftime("%B %d, %Y")
  end

  def time_of
    datetime_of.strftime("%l:%M %p")
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  include ActiveModel::Validations 

  # Associations
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"
  belongs_to :event

  # For batch invites
  attr_accessor :user_ids, :invite_ids

  # Validations
  # Event must be upcoming
  validates_with EventUpcomingValidator
  # Inviter must be the event host
  validates :inviter_id, comparison: { equal_to: Proc.new { |i| i.event.host.id }, message: "You must be the host of this event to invite users!" }
  # Invitee must not be the event host
  validates :invitee_id, comparison: { other_than: Proc.new { |i| i.event.host.id }, message: "You are the host of this event!" }
  # Invitee must be unique to the event
  validates :invitee_id, uniqueness: { scope: :event_id, message: "This user has already been invited to this event!" }
  # Invitee must not be attending already
  validates :invitee_id, exclusion: { in: -> (i) { i.event.attendee_ids }, message: "This user is already attending this event!" }
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!
  before_action -> { authenticate_event_host(params[:event_id]) }, only: [:manage, :create, :revoke]

  # Invitee Actions - Permit only if the current user is logged in
  def index
    @received_invites = current_user.received_invites.includes(:event, :inviter)
  end
  
  def accept
    invite = Invite.find(params[:id])
    attendance = AttendancesCreator.call(attendee_id: current_user.id, event_id: invite.event_id)
    InvitesDestroyer.call(params[:id])
    
    if attendance.success?
      flash[:notice] = "You are now attending this event."
    else
      flash[:alert] = attendance.errors.messages.values.flatten.first
    end 
    redirect_back(fallback_location: invites_path)
  end

  def decline
    InvitesDestroyer.call(params[:id])
    flash[:notice] = "Invite declined."
    redirect_back(fallback_location: invites_path)
  end

  # Inviter Actions - Permit only if the current (logged in) user is the host of the event
  def manage
    @event = Event.find(params[:event_id])
    @invite = Invite.new
    @invitable_users = User.invitable_to(@event)
    @invites = @event.invites.includes(:invitee)
  end

  def create
    invites = InvitesCreator.call(invite_params)

    if invites.successes.present?
      flash[:notice] = "#{invites.successes.count} #{"invite".pluralize(invites.successes.count)} successfully sent."
    end
    if invites.failures.present?
      flash[:alert] = "The following #{"user".pluralize(invites.failures.count)} could not be invited:"
      # Array of usernames that could not be invited
      flash[:failed_invites] = invites.failed_users
    end
    redirect_to event_invites_path
  end

  def revoke
    result = InvitesDestroyer.call(params[:invite_ids])
    unless result.delete_count.zero?
      flash[:notice] = "#{"Invite".pluralize(result.delete_count)} successfully cancelled."
    end
    redirect_to event_invites_path
  end

  private

  def invite_params
    params.require(:invite).permit(user_ids:[]).merge(inviter_id: current_user.id, event_id: params[:event_id])
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_accept_decline.html.erb
<div class="flex gap-1.5">
    <%= button_to "Accept", accept_invite_path(invite), class:"btn btn-blue" %>
    <%= button_to "Decline", decline_invite_path(invite), class:"btn btn-red" %>
</div>

app/views/invites/_create_invites_form.html.erb
<div class="box-gray w-1/2 min-w-fit p-4">
    <% if invitable_users.empty? %>
        <p>There aren't any invitable users at this time!</p>
    <% else %>
        <%= form_with model: invite, url: event_invites_path do |f| %>
            <ul class="text-lg">
                <%= f.collection_check_boxes(:user_ids, invitable_users, :id, :name) do |b| %>
                    <li>
                        <%= b.check_box %>
                        <%= b.label %>
                    </li>
                <% end %>
            </ul>
            <%= f.submit "Invite Users", class:"btn btn-blue mt-5" %>
        <% end %> 
    <% end %>
</div>

app/views/invites/_failed_invites.html.erb
<% if flash[:failed_invites] %>
    <ul class="box-gray border-2 border-red pl-2 pb-2">
        <% flash[:failed_invites].each do |name| %>
            <li class="list-disc ml-5"><%= name %></li>
        <% end %>
    </ul>
<% end %>

app/views/invites/_invite_accept_decline.html.erb
<%= button_to "Accept", accept_invite_path(invite) %>
<%= button_to "Decline", decline_invite_path(invite) %>

app/views/invites/_received_invites.html.erb
<ul>
    <% @received_invites.each do |invite| %>
        <li class="box-gray w-fit p-2 mb-4">
            <%= invite.event.name %>
            <%= "from #{invite.inviter.name}" %>
            <br>
            <%= render "accept_decline", invite: invite %>
        </li>
    <% end %>
</ul>

app/views/invites/_revoke_invites_form.html.erb
<div class="box-gray w-1/2 min-w-fit p-4">
    <% if invites.empty? %>
        <p>There are no pending invitations for this event.</p>
    <% else %>
        <%= form_with url: event_invites_path, method: :delete do |f| %>
            <ul class="text-lg">
                <%= f.collection_check_boxes(:invite_ids, invites, :id, Proc.new {|i| i.invitee.name }) do |b| %>
                    <li>
                        <%= b.check_box %>
                        <%= b.label %>
                    </li>
                <% end %>
            </ul>
            <%= f.submit "Revoke Invites", class:"btn btn-red mt-5" %>
        <% end %>
    <% end %>
</div>

app/views/invites/index.html.erb
<% if @received_invites.any? %>
    <h1>You have <%= pluralize(@received_invites.count, "Invite") %>:</h1>
    <%= render "received_invites", received_invites: @received_invites %>
<% else %>
    <h1>You don't have any invites right now!</h1>
<% end %>

app/views/invites/inviter_index.html.erb
<%= render "failed_invites" %>

<h1>Invite Users to <%= @event.name %></h1>
<%= render "create_invites_form", invite: @invite, invitable_users: @invitable_users %>

<h2>Revoke Invites</h2>
<%= render "revoke_invites_form", invite: @invite, invitees: @invitees %>

app/views/invites/manage.html.erb
<%= render "failed_invites" %>

<h1>Invite Users to <%= @event.name %></h1>
<%= render "create_invites_form", invite: @invite, invitable_users: @invitable_users %>

<h2>Revoke Invites</h2>
<%= render "revoke_invites_form", invites: @invites %>