config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  devise_scope :user do 
    get "users", to: "devise/sessions#new"
  end
  
  # Defines the root path route ("/")
  root "events#index"

  # Users
  resources :users, only: :show
  
  # Events
  resources :events do
    #Invites - Inviters
    resources :invites, only: :create do
      collection do
        get '', to: 'invites#manage' # GET events/:event_id/invites
        delete '', to: 'invites#revoke' # DELETE events/:event_id/invites
      end
    end

    # Attendances
    resources :attendances, only: :create do
      delete '', to: 'attendances#destroy', on: :collection # DELETE events/:event_id/attendances
    end
  end

  # Invites - Invitees
  resources :invites, only: :index do
    member do
      post 'accept' # POST invites/:id/accept
      post 'decline' # POST invites/:id/decline
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include Attendable

  validates :name, :datetime_of, :location, presence: true 
  validates :datetime_of, comparison: { greater_than: DateTime.current, message: "must be in the future!" }
  
  belongs_to :host, class_name: "User"
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances

  has_many :invites, dependent: :destroy
  has_many :invitees, through: :invites

  attr_accessor :current_user

  # Past/Future Events
  scope :past, -> { where("datetime_of < ?", DateTime.now) }
  scope :future, -> { where("datetime_of > ?", DateTime.now) }

  # Format Event Date/Time
  def date_of
    datetime_of.strftime("%B %d, %Y")
  end

  def time_of
    datetime_of.strftime("%l:%M %p")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { authenticate_event_host(params[:id]) }, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosted_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    @event.current_user = current_user 
    @invite = @event.invites.find_by(invitee: current_user) 
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:notice] = "Event successfully deleted."
    redirect_to root_path
  end

  private 

  def event_params
    params.require(:event).permit([:name, :datetime_of, :location, :is_private, :description])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<!-- If EventsController is able to find an invite to this event for the current user-->
<% if invite %>
    <div class="flex justify-end">
        <div class="box-gray flex flex-col items-end p-2 w-fit">
            <p><%= "#{invite.inviter.name} has invited you to this event!" %></p>
            <%= render "invites/accept_decline", invite: invite %>
        </div>
    </div>
<% elsif event.is_private? %>
    <p class="box-gray p-2 text-left">This event is private.</p>
<% elsif event.attendable? %>
    <%= button_to "Attend this Event", event_attendances_path(event.id), class: "btn btn-blue" %>
<% end %>

app/views/events/_errors.html.erb
<% unless event.errors.empty? %>
    <div class="box-gray border-2 border-red pl-2 pb-2">
        <h2><%= "#{pluralize(event.errors.count, 'Error')}:"%></h2>
        <ul class="list-disc ml-5">
            <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/events/_event.html.erb
<li class="box-gray flex flex-col p-4 pt-2">
    <h3><%= event.name %></h3>
    <p class="text-xs border-b pb-2"><%= event.date_of %></p>
    <p class="py-2 flex-grow"><%= event.description.truncate(150, separator: ' ') %></p>
    <%= link_to "Event Details", event, 
        class: "border rounded text-center py-1 hover:bg-white hover:text-black" %>
</li>

app/views/events/_event_attend.html.erb
<!-- If EventsController is able to find an invite to this event for the current user-->
<% if invite %>
    <p><%= "#{invite.inviter.name} has invited you to this event!" %></p>
    <%= render "invites/invite_accept_decline", invite: invite %>
<% elsif event.is_private? %>
    <p>This event is private.</p>
<% elsif event.attendable? %>
    <%= button_to "Attend this Event", event_attendances_path(event.id) %>
<% end %>

app/views/events/_event_errors.html.erb
<% unless event.errors.empty? %>
    <h2><%= "#{pluralize(event.errors.count, 'Error')}:"%></h2>
    <ul>
        <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/events/_event_form.html.erb
<%= form_with model: event do |f| %>
    <div>
        <%= f.label :name, "Event Name:" %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :datetime_of, "Event Date/Time:" %>
        <%= f.datetime_field :datetime_of, min: DateTime.now.strftime("%Y-%m-%d, %I:%M %P") %>
    </div>

    <div>
        <%= f.label :location, "Event Location:" %>
        <%= f.text_field :location %>
    </div>

    <div>
        <%= f.check_box :is_private %>
        <%= f.label :is_private, "Make this event private?" %>
    </div>

    <div>
        <%= f.label :description, "Description:" %>
        <%= f.text_area :description, size: "50x10" %>
    </div>
    
    <div><%= f.submit %></div>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
    <div class="box-gray p-2 flex flex-col gap-2">
        <div class="flex flex-col">
            <%= f.label :name, "Event Name: *", class:"" %>
            <%= f.text_field :name, class:"w-full" %>
        </div>

        <div class="flex flex-col">
            <%= f.label :datetime_of, "Event Date/Time: *", class:"" %>
            <%= f.datetime_field :datetime_of, min: DateTime.now.strftime("%Y-%m-%d, %I:%M %P"), class:"w-full" %>
        </div>
        
        <div class="flex flex-col">
            <%= f.label :location, "Event Location: *", class:"" %>
            <%= f.text_field :location, class:"w-full" %>
        </div>
    
        <div class="flex items-center gap-2">
            <%= f.label :is_private, "Make this event private:" %>
            <%= f.check_box :is_private, class:"" %>
        </div>
        <div class="flex flex-col">
            <%= f.label :description, "Description:", class:"" %>
            <%= f.text_area :description, size: "30x5", placeholder:"Describe your event!", class:"" %>
        </div>

        <div class="flex justify-end mt-5">
            <%= f.submit class:"btn btn-blue" %>
        </div>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit this Event:</h1>
<p>Required fields are marked with <abbr title="required">*:</abbr></p>

<div class="w-1/2 min-w-fit">
    <%= render "errors", event: @event %>
    
    <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<div class="flex justify-between items-center">
    <h1>Upcoming Events</h1>
    <%= link_to "Create an Event", new_event_path, class: "btn btn-blue" %>
</div>
<ul class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
    <%= render @events.future %>
</ul>

<h2>Past Events</h2>
<ul class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-10">
    <%= render @events.past %>
</ul>

app/views/events/new.html.erb
<h1>Create a New Event:</h1>
<p>Required fields are marked with <abbr title="required">*:</abbr></p>

<div class="w-1/2 min-w-fit">
    <%= render "errors", event: @event %>
    
    <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<div class="flex flex-col sm:flex-row justify-between items-end">
    <h1 class="self-start"><%= @event.name %></h1>

    <!-- Edit/Delete Event; Manage Invites (Create/Revoke) -->
    <% if current_user == @event.host %>
        <div class="flex pb-5 gap-x-2.5">
            <%= link_to "Manage Invites", event_invites_path(@event), class:"btn btn-gray" %>
            <%= link_to "Edit Event", edit_event_path, class: "btn btn-blue" %>
            <%= button_to "Delete Event", event_path, form: { data: { turbo_confirm: "Are you sure you want to delete this event?" } }, method: :delete,
                class: "btn btn-red" %>
        </div>
    <% end %>
</div>

<!-- Event Details -->
<div class="box-gray flex flex-col sm:flex-row gap-8 p-4">
    <p class="flex-grow"><%= @event.description %></p>
    <div class="whitespace-nowrap">
        <p>Created by <%= @event.host.name %></p>
        <p>Date/Time: <%= "#{@event.date_of} at #{@event.time_of}" %></p>
        <p>Location: <%= @event.location %></p>
    </div>
</div>

<!-- Event Attendance -->
<div class="mt-5 text-right">
    <%= render "attend", event: @event, invite: @invite %>
</div>

<!-- List of Attendees -->
<h2><%= @event.attendees.count %> Attending this Event:</h2>
<ul class="box-gray p-2">
    <% if @event.attendees.empty? %>
        <p>This event has no attendees yet.</p>
    <% end %>
    <% @event.attendees.each do |user| %>
        <li><%= user.name %></li>
    <% end %>
</ul>


<!-- Cancel Attendance -->
<% if @event.attendees.include?(current_user) %>
    <div class="text-right">
        <%= button_to "Cancel Attendance", event_attendances_path(@event.id), method: :delete,
            class: "btn btn-red mt-4" %>
    </div>
<% end %>