config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  devise_scope :user do 
    get "users", to: "devise/sessions#new"
  end
  
  # Defines the root path route ("/")
  root "events#index"

  # Users
  resources :users, only: :show
  
  # Events
  resources :events do
    #Invites - Inviters
    resources :invites, only: :create do
      collection do
        get '', to: 'invites#manage' # GET events/:event_id/invites
        delete '', to: 'invites#revoke' # DELETE events/:event_id/invites
      end
    end

    # Attendances
    resources :attendances, only: :create do
      delete '', to: 'attendances#destroy', on: :collection # DELETE events/:event_id/attendances
    end
  end

  # Invites - Invitees
  resources :invites, only: :index do
    member do
      post 'accept' # POST invites/:id/accept
      post 'decline' # POST invites/:id/decline
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar">
    <div class="container flex justify-between">
        <%= link_to "Home", root_path %>

        <!--Hamburger Menu -->
        <div class="text-right">
            <!--Hamburger Icon -->
            <%= label_tag :hamburger, "☰", class:"sm:hidden text-2xl cursor-pointer" %>
            <%= check_box_tag :hamburger, 'checked', false, class:"hidden" %>

            <!--Hamburger Items-->
            <ul class="hamburger-items hidden sm:flex">
                <% if user_signed_in? %>
                    <li><%= link_to "My Events", current_user %></li>
                    <li><%= link_to "My Invites (#{current_user.received_invites.count})", invites_path %></li>
                    <li><%= link_to current_user.name, edit_user_registration_path %></li>
                    <li><%= button_to "Log Out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Log In", new_user_session_path %></li>
                    <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full bg-dark-gray text-white">
    <%= render "layouts/header" %>

    <div class="container pb-10">
      <% if notice %>
        <div class="bg-green my-2 p-2 rounded text-black"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="bg-light-red my-2 p-2 rounded text-black"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>